# Generated by Django 5.1 on 2024-08-10 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_imangemodel_delete_student'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ImangeModel',
            new_name='ImageModel',
        ),
    ]
