# Generated by Django 5.1 on 2024-08-10 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_rename_imangemodel_imagemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagemodel',
            name='thumbnail_mini',
            field=models.ImageField(blank=True, null=True, upload_to='images/thumbnails'),
        ),
    ]
