# Generated by Django 5.1 on 2024-08-10 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_imagemodel_thumbnail_mini'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagemodel',
            name='thumbnail_xllarge',
            field=models.ImageField(blank=True, null=True, upload_to='images/thumbnails'),
        ),
    ]
