# Generated by Django 5.1 on 2024-08-10 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_imagemodel_thumbnail_xllarge'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagemodel',
            name='thumbnail_8k',
            field=models.ImageField(blank=True, null=True, upload_to='images/thumbnails'),
        ),
    ]
